"""Build the morning check-in worklist (generation-design.md): run the verifier
over the full v2 output and write a triaged docs/v2/worklist.md.

    uv run --with pymupdf python pipeline/generate/worklist.py
"""

import json
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE.parents[0] / "verifier"))
sys.path.insert(0, str(HERE))

import calibrate  # noqa: E402

REPO = calibrate.REPO
OUT = REPO / "cards/anthropic/claude-fable-5/sections"
WL = REPO / "docs/v2/worklist.md"


def main():
    generated = sorted(int(p) for p in json.loads((REPO / "pipeline/.cache/genpages.json").read_text())) \
        if (REPO / "pipeline/.cache/genpages.json").exists() else None
    flags = calibrate.collect_flags(str(OUT))
    by = Counter((f["invariant"], f["severity"]) for f in flags)
    majors = [f for f in flags if f["severity"] == "major"]
    maj_by_inv = Counter(f["invariant"] for f in majors)

    lines = ["# v2 conversion worklist", "",
             "Auto-generated by `pipeline/generate/worklist.py` — the morning check-in",
             "artifact (generation-design.md). Mechanical assembly only; LLM alt-text /",
             "adjudication passes not yet run.", "",
             "## Gate summary (full v2 output)", ""]
    for (inv, sev), n in sorted(by.items()):
        lines.append(f"- {inv} {sev}: {n}")
    lines += ["", f"**Major flags: {len(majors)}** " + ", ".join(f"{k}={v}" for k, v in sorted(maj_by_inv.items())), ""]

    lines += ["## Major flags by page", ""]
    for f in sorted(majors, key=lambda f: (f["page"], f["invariant"]))[:200]:
        d = json.dumps(f["detail"], ensure_ascii=False)
        if len(d) > 160:
            d = d[:160] + "…"
        lines.append(f"- p.{f['page']} [{f['invariant']}] {d}")

    lines += ["", "## Known gaps (not regressions — designed-deferred)", "",
              "- **Figure alt text**: empty pending the LLM alt-text pass.",
              "- **Goto link destinations**: emitted as `DEST:<page>`; L2 resolution",
              "  (page→section anchor, mine v1's apply_internal_links.py logic) pending.",
              "- **Footnote refs inside table cells**: docling flattens cell `<sup>`s;",
              "  v1 added them manually. Affects the FN1 ref count on table pages.",
              "- **Figure/chip legends**: standalone legend rows (e.g. p.44 R&D key)",
              "  not yet captured as blocks.",
              "- **Transcript tool-output / code inside turns**: minimal handling.", ""]

    WL.write_text("\n".join(lines))
    print(f"wrote {WL}: {len(majors)} major flags, {len(flags)} total")
    for k, v in sorted(maj_by_inv.items()):
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
